<form action="<?php echo _url('extension', 'configure', 'e', urlencode($this->getName())); ?>" method="post">
	<input type="hidden" name="_csrf" value="<?php echo FreshRSS_Auth::csrfToken(); ?>" />
	<div class="form-group">
		<label class="group-name" for="rss_bridge_url"><?php echo _t('ext.rssbridge.url'); ?></label>
		<div class="group-controls">
			<input type="url" name="rss_bridge_url" id="rss_bridge_url" value="<?php echo FreshRSS_Context::$user_conf->rss_bridge_url; ?>">
		</div>
	</div>

	<div class="form-group form-actions">
		<div class="group-controls">
			<button type="submit" class="btn btn-important"><?php echo _t('gen.action.submit'); ?></button>
			<button type="reset" class="btn"><?php echo _t('gen.action.cancel'); ?></button>
		</div>
	</div>
</form>
